[package]
name = "loy-typecheck"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
loy-context.workspace = true
loy-typecheck-ast.workspace = true
loy-ast.workspace = true