[package]
name = "loy-ast"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
miette.workspace = true
thiserror.workspace = true