[workspace]
resolver = "2"
members = [
    "piller-lexer",
    "piller-parser",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["wiru <hello@wiru.st>"]
repository = "https://github.com/wllfaria/piller"

[workspace.dependencies]
piller-lexer = { path = "piller-lexer" }
piller-parser = { path = "piller-parser" }
thiserror = "2.0.16"
miette = { version = "7.6.0", features = ["fancy"] }

[package]
name = "scratch"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
piller-lexer.workspace = true
piller-parser.workspace = true
miette.workspace = true