[package]
name = "piller-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
piller-lexer.workspace = true
thiserror.workspace = true
miette.workspace = true