[package]
name = "loy-context"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
loy-ast.workspace = true
fxhash = "0.2.1"
parking_lot = "0.12.4"